In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv("crop_dataset.csv")

# Display basic info and first few rows
print(df.info())
print(df.head())

# Check for missing values
print("Missing Values:\n", df.isnull().sum())

# Summary statistics
print("Summary Statistics:\n", df.describe())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Temperature_C        1000 non-null   float64
 1   Humidity_%           1000 non-null   float64
 2   Soil_Temperature_C   1000 non-null   float64
 3   Soil_pH              1000 non-null   float64
 4   Soil_Nitrogen_ppm    1000 non-null   float64
 5   Soil_Phosphorus_ppm  1000 non-null   float64
 6   Soil_Potassium_ppm   1000 non-null   float64
 7   Crop_Type            1000 non-null   object 
dtypes: float64(7), object(1)
memory usage: 62.6+ KB
None
   Temperature_C  Humidity_%  Soil_Temperature_C   Soil_pH  Soil_Nitrogen_ppm  \
0      22.494481   55.553988           21.140468  6.672703          61.479629   
1      29.408572   66.257028           20.963746  6.796681          82.488910   
2      26.783927   76.188375           28.875055  6.250468          78.414484   
3      25.183

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv("crop_dataset.csv")

# Encode categorical variable (Crop_Type: Tomato -> 0, Capsicum -> 1)
encoder = LabelEncoder()
df["Crop_Type"] = encoder.fit_transform(df["Crop_Type"])

# Select features and target
X = df.drop(columns=["Crop_Type"])  # Features
y = df["Crop_Type"]  # Target variable

# Feature Scaling (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Preprocessing Completed!")
print(f"Training Set: {X_train.shape}, Testing Set: {X_test.shape}")


Preprocessing Completed!
Training Set: (800, 7), Testing Set: (200, 7)


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", report)


Model Accuracy: 0.87

Confusion Matrix:
 [[133  13]
 [ 13  41]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.91      0.91       146
           1       0.76      0.76      0.76        54

    accuracy                           0.87       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.87      0.87      0.87       200



In [5]:
import pickle

# Save the trained model
model_filename = "crop_prediction_model.pkl"
with open(model_filename, "wb") as file:
    pickle.dump(model, file)

print(f"Model saved as {model_filename}")


Model saved as crop_prediction_model.pkl


In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("crop_dataset.csv")

# Check the count of each crop type
print(df["Crop_Type"].value_counts())

# Verify encoding (Tomato = 0, Capsicum = 1)
df_encoded = df.copy()
df_encoded["Crop_Type"] = df_encoded["Crop_Type"].astype("category").cat.codes
print(df_encoded["Crop_Type"].value_counts())


Capsicum    712
Tomato      288
Name: Crop_Type, dtype: int64
0    712
1    288
Name: Crop_Type, dtype: int64


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv("balanced_crop_dataset.csv")

# Encode categorical variable (Crop_Type: Tomato -> 0, Capsicum -> 1)
encoder = LabelEncoder()
df["Crop_Type"] = encoder.fit_transform(df["Crop_Type"])

# Select features and target
X = df.drop(columns=["Crop_Type"])  # Features
y = df["Crop_Type"]  # Target variable

# Feature Scaling (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Preprocessing Completed!")
print(f"Training Set: {X_train.shape}, Testing Set: {X_test.shape}")

Preprocessing Completed!
Training Set: (460, 7), Testing Set: (116, 7)


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", report)

Model Accuracy: 0.84

Confusion Matrix:
 [[44  9]
 [10 53]]

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.83      0.82        53
           1       0.85      0.84      0.85        63

    accuracy                           0.84       116
   macro avg       0.83      0.84      0.84       116
weighted avg       0.84      0.84      0.84       116



In [5]:
import pickle

# Save the trained model
model_filename = "crop_prediction.pkl"
with open(model_filename, "wb") as file:
    pickle.dump(model, file)

print(f"Model saved as {model_filename}")

Model saved as crop_prediction.pkl


In [6]:
import pandas as pd

# Load the dataset
df = pd.read_csv("crop_dataset.csv")

# Separate Tomato and Capsicum datasets
df_tomato = df[df["Crop_Type"] == "Tomato"]
df_capsicum = df[df["Crop_Type"] == "Capsicum"]

# Save the datasets
df_tomato.to_csv("tomato_dataset.csv", index=False)
df_capsicum.to_csv("capsicum_dataset.csv", index=False)

print("Tomato and Capsicum datasets saved successfully!")


Tomato and Capsicum datasets saved successfully!


In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pandas as pd

# Load two datasets
df_tomato = pd.read_csv("tomato.csv")
df_capsicum = pd.read_csv("capsicum.csv")

# Combine both datasets into one
df = pd.concat([df_tomato, df_capsicum], ignore_index=True)

# Encode categorical variable (Crop_Type: Tomato -> 0, Capsicum -> 1)
encoder = LabelEncoder()
df["Crop_Type"] = encoder.fit_transform(df["Crop_Type"])

# Select features and target
X = df.drop(columns=["Crop_Type","Date","Soil_Type","Wind_Speed","Soil_Quality","Area","Crop_Yield"])  # Features
y = df["Crop_Type"]  # Target variable

# Feature Scaling (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Preprocessing Completed!")
print(f"Training Set: {X_train.shape}, Testing Set: {X_test.shape}")


Preprocessing Completed!
Training Set: (4921, 6), Testing Set: (1231, 6)


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", report)

Model Accuracy: 1.00

Confusion Matrix:
 [[488   0]
 [  0 743]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       488
           1       1.00      1.00      1.00       743

    accuracy                           1.00      1231
   macro avg       1.00      1.00      1.00      1231
weighted avg       1.00      1.00      1.00      1231



In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", report)

# ==========================
# TESTING PART: User Input
# ==========================

import numpy as np

# Get user input for testing
print("\nEnter the environmental conditions for crop prediction:")

temperature = float(input("Temperature: "))
humidity = float(input("Humidity: "))
soil_pH = float(input("Soil_pH: "))
soil_nitrogen = float(input("N: "))
soil_phosphorus = float(input("P: "))
soil_potassium = float(input("K: "))


# Prepare input for model
user_input = np.array([[temperature, humidity, soil_pH, soil_nitrogen, 
                        soil_phosphorus, soil_potassium]])

# Apply the same scaling as training data
user_input_scaled = scaler.transform(user_input)

# Make prediction
prediction = model.predict(user_input_scaled)

# Convert prediction to readable label
predicted_crop = "Tomato" if prediction[0] == 0 else "Capsicum"

print(f"\n✅ Predicted Crop: {predicted_crop}")


Model Accuracy: 1.00

Confusion Matrix:
 [[488   0]
 [  0 743]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       488
           1       1.00      1.00      1.00       743

    accuracy                           1.00      1231
   macro avg       1.00      1.00      1.00      1231
weighted avg       1.00      1.00      1.00      1231


Enter the environmental conditions for crop prediction:
Temperature: 28.0677181
Humidity: 68.53302064
Soil_pH: 6.760882808
N: 19.95483611
P: 17.29033743
K: 198.9564808

✅ Predicted Crop: Tomato


C:\Users\Dilshan Dananjaya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Load dataset
capsicum_df = pd.read_csv("capsicum.csv")
tomato_df = pd.read_csv("tomato.csv")

# Add a Crop column
tomato_df["Crop"] = "Tomato"
capsicum_df["Crop"] = "Capsicum"

# Select features
features = ["Temperature", "Humidity", "Soil_pH", "N", "P", "K", "Crop"]
crop_data = pd.concat([tomato_df[features], capsicum_df[features]], ignore_index=True)

# Shuffle dataset
crop_data = crop_data.sample(frac=1, random_state=42).reset_index(drop=True)

# Prepare features and labels
X = crop_data.drop(columns=["Crop"])
y = crop_data["Crop"]

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the model
model = RandomForestClassifier(n_estimators=200, random_state=42, max_depth=10)
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2%}")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Save the model and encoders
joblib.dump(model, "crop_prediction_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

print("Model and encoders saved successfully!")

# Load the model for testing
def predict_crop(temp, humidity, ph, n, p, k):
    model = joblib.load("crop_prediction_model.pkl")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")
    
    input_data = np.array([[temp, humidity, ph, n, p, k]])
    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)
    predicted_crop = label_encoder.inverse_transform(prediction)[0]
    
    return predicted_crop

# Example test case
example_prediction = predict_crop(23.83013916, 75.28104911,5.906320077, 184.1614516, 100.0255129, 57.25166425)
print(f"Predicted Crop: {example_prediction}")

Model Accuracy: 100.00%
              precision    recall  f1-score   support

    Capsicum       1.00      1.00      1.00       528
      Tomato       1.00      1.00      1.00       703

    accuracy                           1.00      1231
   macro avg       1.00      1.00      1.00      1231
weighted avg       1.00      1.00      1.00      1231

Model and encoders saved successfully!
Predicted Crop: Tomato


C:\Users\Dilshan Dananjaya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
